# Data Preprocessing Project

This notebook demonstrates data loading and exploration using a dataset from Kaggle.

<div class="alert alert-block alert-info">
    1. Import <b>Libraries</b>
</div>

In [47]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os

<div class="alert alert-block alert-info">
    2. <b>Data Loading/Reading</b>
</div>

In [48]:
df = pd.read_csv("data.csv")

<div class="alert alert-block alert-info">
    3. <b>Data Exploration</b>
</div>

In [49]:
df.head(5)

,User_ID,Age_Years,Gender,Body_Mass_KG,Height_CM,Steps,Workout_Minutes,Exercise_Type,Avg_Heart_Rate,Intensity_Score,Calories_Burned,Notes,Calories
0,1,56.0,Male,90.0,187,6503.0,105.0,Weightlifting,85.0,4.0,2291.0,NaN,2273.0
1,2,46.0,Female,51.0,161,3217.0,110.0,Swimming,178.0,5.0,2704.0,Session 1,2673.0
2,3,32.0,Male,86.0,160,4474.0,73.0,Weightlifting,135.0,1.0,1548.0,Session 2,1566.0
3,4,60.0,Male,94.0,197,2929.0,110.0,Weightlifting,90.0,1.0,1736.0,Session 3,1749.0
4,5,25.0,Male,97.0,198,9958.0,110.0,HIIT,175.0,6.0,3001.0,Session 4,3039.0

In [50]:
df.tail(5)

,User_ID,Age_Years,Gender,Body_Mass_KG,Height_CM,Steps,Workout_Minutes,Exercise_Type,Avg_Heart_Rate,Intensity_Score,Calories_Burned,Notes,Calories
4995,4996,33.0,Female,66.0,153,6806.0,31.0,HIIT,96.0,2.0,1355.0,Session 4995,1349.0
4996,4997,22.0,Male,67.0,160,8844.0,105.0,HIIT,111.0,5.0,2550.0,Session 4996,2566.0
4997,4998,38.0,Male,106.0,196,13683.0,111.0,Yoga,174.0,3.0,2799.0,Session 4997,2756.0
4998,4999,27.0,Female,86.0,164,10343.0,26.0,Running,86.0,7.0,2144.0,Session 4998,2184.0
4999,5000,36.0,Female,109.0,179,5231.0,71.0,Swimming,93.0,3.0,1865.0,Session 4999,1878.0

In [51]:
df.shape

(5000, 13)

In [52]:
df.columns

Index(['User_ID', 'Age_Years', 'Gender', 'Body_Mass_KG', 'Height_CM', 'Steps',
       'Workout_Minutes', 'Exercise_Type', 'Avg_Heart_Rate', 'Intensity_Score',
       'Calories_Burned', 'Notes', 'Calories'],
      dtype='object')

In [53]:
df = df.rename(columns={
    "Age_Years": "Age",
    "Body_Mass_KG": "Body_Mass",
    "Height_CM": "Height"
})

In [54]:
df.count()

User_ID            5000
Age                4945
Gender             4945
Body_Mass          4945
Height             5000
Steps              4945
Workout_Minutes    4945
Exercise_Type      4945
Avg_Heart_Rate     4945
Intensity_Score    4945
Calories_Burned    4750
Notes              4500
Calories           4945
dtype: int64

In [55]:
df.describe()

,User_ID,Age,Body_Mass,Height,Steps,Workout_Minutes,Avg_Heart_Rate,Intensity_Score,Calories_Burned,Calories
count,5000.000000,4945.000000,4945.000000,5000.000000,4945.000000,4945.000000,4945.000000,4945.000000,4750.00000,4945.000000
mean,2500.500000,41.141759,84.534479,174.257000,8523.711426,66.549242,120.744590,5.085541,2284.64800,2283.951871
std,1443.520003,13.526804,20.069138,14.553725,3783.565063,30.494065,34.790416,2.568354,525.11538,523.573309
min,1.000000,18.000000,50.000000,150.000000,2001.000000,15.000000,60.000000,1.000000,760.00000,763.000000
25%,1250.750000,29.000000,67.000000,162.000000,5237.000000,41.000000,91.000000,3.000000,1903.00000,1906.000000
50%,2500.500000,41.000000,84.000000,174.000000,8592.000000,66.000000,121.000000,5.000000,2279.00000,2281.000000
75%,3750.250000,53.000000,102.000000,187.000000,11799.000000,93.000000,151.000000,7.000000,2661.00000,2657.000000
max,5000.000000,64.000000,119.000000,199.000000,14998.000000,119.000000,179.000000,9.000000,3704.00000,3740.000000

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          5000 non-null   int64
 1   Age              4945 non-null   float64
 2   Gender           4945 non-null   object
 3   Body_Mass        4945 non-null   float64
 4   Height           5000 non-null   int64
 5   Steps            4945 non-null   float64
 6   Workout_Minutes  4945 non-null   float64
 7   Exercise_Type    4945 non-null   object
 8   Avg_Heart_Rate   4945 non-null   float64
 9   Intensity_Score  4945 non-null   float64
 10  Calories_Burned  4750 non-null   float64
 11  Notes            4500 non-null   object
 12  Calories         4945 non-null   float64
dtypes: float64(8), int64(2), object(3)
memory usage: 507.9+ KB

In [57]:
print(f"Number of Rows: {df.shape[0]} and Number of Columns: {df.shape[1]}")

Number of Rows: 5000 and Number of Columns: 13

In [58]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [59]:
df.nunique()

User_ID            5000
Age                  47
Gender                2
Body_Mass            70
Height               50
Steps              4118
Workout_Minutes     105
Exercise_Type         6
Avg_Heart_Rate      120
Intensity_Score       9
Calories_Burned    1899
Notes              4500
Calories           1915
dtype: int64

In [60]:
df.isnull().sum()

User_ID              0
Age                 55
Gender              55
Body_Mass           55
Height               0
Steps               55
Workout_Minutes     55
Exercise_Type       55
Avg_Heart_Rate      55
Intensity_Score     55
Calories_Burned    250
Notes              500
Calories            55
dtype: int64

<div class="alert alert-block alert-info">
    4. <b>Data Pre-Processing</b>
</div>

<div class="alert alert-block alert-warning">
    4.1. <b>Manage Null Values</b>
</div>

In [61]:
df.drop(['Notes', 'Calories_Burned'], axis=1, inplace=True)

In [62]:
df['Calories'].mean()

np.float64(2283.95187057634)

In [63]:
df['Calories'].mode().iloc[0]

np.float64(2423.0)

In [64]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
print(df['Gender'])

0         Male
1       Female
2         Male
3         Male
4         Male
         ...
4995    Female
4996      Male
4997      Male
4998    Female
4999    Female
Name: Gender, Length: 5000, dtype: object

In [65]:
df['Exercise_Type'] = df['Exercise_Type'].fillna(df['Exercise_Type'].mode()[0])
print(df['Exercise_Type'])

0       Weightlifting
1            Swimming
2       Weightlifting
3       Weightlifting
4                HIIT
            ...
4995             HIIT
4996             HIIT
4997             Yoga
4998          Running
4999         Swimming
Name: Exercise_Type, Length: 5000, dtype: object

In [66]:
def fillnaObjectMode(cols):
    for col in cols:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 'Unknown')

object_cols = [
    'Gender', 'Exercise_Type'
]

fillnaObjectMode(object_cols)

In [67]:
def fillnaNumericMode(cols):
    for col in cols:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 0)

numeric_cols = ['User_ID', 'Age', 'Body_Mass', 'Height', 'Steps', 'Workout_Minutes', 'Avg_Heart_Rate', 'Intensity_Score', 'Calories']
fillnaNumericMode(numeric_cols)

print("\nNull Values After Filling:")
print(df.isnull().sum())

Null Values After Filling:
User_ID            0
Age                0
Gender             0
Body_Mass          0
Height             0
Steps              0
Workout_Minutes    0
Exercise_Type      0
Avg_Heart_Rate     0
Intensity_Score    0
Calories           0
dtype: int64

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          5000 non-null   int64
 1   Age              5000 non-null   float64
 2   Gender           5000 non-null   object
 3   Body_Mass        5000 non-null   float64
 4   Height           5000 non-null   int64
 5   Steps            5000 non-null   float64
 6   Workout_Minutes  5000 non-null   float64
 7   Exercise_Type    5000 non-null   object
 8   Avg_Heart_Rate   5000 non-null   float64
 9   Intensity_Score  5000 non-null   float64
 10  Calories         5000 non-null   float64
dtypes: float64(7), int64(2), object(2)
memory usage: 429.8+ KB

<div class="alert alert-block alert-warning">
    4.2. <b>Manage Data Types</b>
</div>

In [69]:
df['Calories'] = df['Calories'].astype('int32')

In [70]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce').fillna(0).astype('int32')

In [71]:
df['Body_Mass'] = pd.to_numeric(df['Body_Mass'], errors='coerce').fillna(0).astype('int32')

In [72]:
def CHANGEFLOATTOINT(cols):
    for i in cols:
        df[i] = df[i].astype('int32')

int_columns = ['User_ID', 'Height', 'Steps', 'Workout_Minutes', 'Avg_Heart_Rate', 'Intensity_Score']
CHANGEFLOATTOINT(int_columns)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          5000 non-null   int32
 1   Age              5000 non-null   int32
 2   Gender           5000 non-null   object
 3   Body_Mass        5000 non-null   int32
 4   Height           5000 non-null   int32
 5   Steps            5000 non-null   int32
 6   Workout_Minutes  5000 non-null   int32
 7   Exercise_Type    5000 non-null   object
 8   Avg_Heart_Rate   5000 non-null   int32
 9   Intensity_Score  5000 non-null   int32
 10  Calories         5000 non-null   int32
dtypes: int32(9), object(2)
memory usage: 254.0+ KB

In [74]:
def CHANGEObjectTOINT(cols):
    for i in cols:
        data = pd.DataFrame({i: df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))
        df[i] = data_LE.transform(df[i])

categorical_columns = ['Gender', 'Exercise_Type']
CHANGEObjectTOINT(categorical_columns)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          5000 non-null   int32
 1   Age              5000 non-null   int32
 2   Gender           5000 non-null   int64
 3   Body_Mass        5000 non-null   int32
 4   Height           5000 non-null   int32
 5   Steps            5000 non-null   int32
 6   Workout_Minutes  5000 non-null   int32
 7   Exercise_Type    5000 non-null   int64
 8   Avg_Heart_Rate   5000 non-null   int32
 9   Intensity_Score  5000 non-null   int32
 10  Calories         5000 non-null   int32
dtypes: int32(9), int64(2)
memory usage: 254.0 KB

In [76]:
df.head(2)

,User_ID,Age,Gender,Body_Mass,Height,Steps,Workout_Minutes,Exercise_Type,Avg_Heart_Rate,Intensity_Score,Calories
0,1,56,1,90,187,6503,105,4,85,4,2273
1,2,46,0,51,161,3217,110,3,178,5,2673

In [77]:
df.to_csv('processed_data.csv', index=False, header=True)

In [78]:
df = pd.read_csv('processed_data.csv')

In [79]:
print(os.getcwd())  
print(os.listdir())

s:\SEMESTER 3\AI(Lab)\Project
['.env', 'data.csv', 'model_rf.pkl', 'preprocessing.ipynb', 'processed_data.csv', 'requirements.txt', 'templates']

<div class="alert alert-block alert-info">
    5. <b>Train - Test Splitting</b>
</div>

In [80]:
df = pd.read_csv('processed_data.csv')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          5000 non-null   int64
 1   Age              5000 non-null   int64
 2   Gender           5000 non-null   int64
 3   Body_Mass        5000 non-null   int64
 4   Height           5000 non-null   int64
 5   Steps            5000 non-null   int64
 6   Workout_Minutes  5000 non-null   int64
 7   Exercise_Type    5000 non-null   int64
 8   Avg_Heart_Rate   5000 non-null   int64
 9   Intensity_Score  5000 non-null   int64
 10  Calories         5000 non-null   int64
dtypes: int64(11)
memory usage: 429.8 KB

In [82]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Body_Mass', 'Height', 'Steps',
       'Workout_Minutes', 'Exercise_Type', 'Avg_Heart_Rate', 'Intensity_Score',
       'Calories'],
      dtype='object')

In [83]:
X = df.drop('Calories', axis=1)   
Y = df['Calories']

In [84]:
train_x, test_X, train_y, test_y = train_test_split(X, Y, test_size=0.2, shuffle=False)

In [85]:
print(train_x.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(4000, 10) (4000,)
(1000, 10) (1000,)

<div class="alert alert-block alert-info">
    6. <b>Applying Classifier / Model Training</b>
</div>

In [86]:
model_rf = LinearRegression()

In [87]:
model_rf.fit(train_x, train_y)
print(model_rf)

LinearRegression()

In [88]:
predictions = model_rf.predict(test_X)
model_pred_rf = predictions
print(predictions)

[2307.68075523 2221.12514977 2233.7555951  1564.46976262 2322.43673049
 2895.75947234 1763.75569899 2641.13602842 1711.71077442 2098.67476925
 2200.80176055 1968.57265541 2980.65884877 1839.59598014 1070.224535
 2653.025606   2577.65751733 1883.39767384 2362.04995746 2754.03124647
 1465.44861743 2329.21389923 2799.00700719 2352.02514862 3026.16899691
 2637.59418993 1645.94055684 2567.26427983 2208.57930063 1716.6327832
 1768.96882264 2593.77975829 1891.07977529 2518.48484415 1995.96450059
 1425.18534606 2117.40947032 3179.96453408 2719.32293916 2414.50237001
 2157.14342759 2339.19033577 2506.44480985 1923.91464839 2642.82383071
 2495.57747792 2025.5924258  2485.72454803 2300.01662547 2184.1332927
 2033.36736705 1947.74194086 1832.8695296  2917.445362   2163.98575075
 2647.20832812 3074.44785754 2618.77358096 2436.91190572 2245.76842259
 1527.97694634 2390.83166226 2397.89629258 2329.95334965 2941.14934167
 2061.6109212  2509.57424595 1650.08722649 3182.01858281 2954.02253569
 1847.43773163 1790.49393708 3370.86599574 2158.77726752 1423.96339329
 2557.0812799  1233.61077722 1842.35257402 2702.16681781 2095.97201933
 2995.60467235 1638.15614106 2340.98243394 1850.14357937 2796.70194187
 2051.53852589 2793.67691247 2244.44646063 1305.62241088 2162.19444411
 2980.02158072 2546.2968818  1668.75369161 2796.22457202 3181.25465753
 2271.53459915 2890.1991618  2036.61959912 2895.16931754 2040.47793697
 1675.10286374 2392.35828736 2095.56859198 2171.14935995 1805.58884828
 2350.86134664 2258.42930849 2754.92468705 2613.80502516 1486.41333528
 2991.70268097 2349.40883013 2307.80234129 2674.14628495 1814.94786353
 2274.07482414 1995.71988742 1390.65724253 3309.75750335 1929.7680039
 2117.73700491 2467.80172384 1621.91379471 2382.04245232 1368.88144713
 2063.03165621 2735.98143993 2336.47183178 1067.37616038 2692.4574737
 2266.62847857 1680.02258876 2667.91663272 3122.21739285 2820.88877889
 1193.54454016 3174.39359739 2339.57219192 2634.29791466 3467.70833484
 3094.11691122 2640.12647868 2405.13450267 2353.48918513 1885.01380747
 1913.43569876 1951.17646    2281.57515795 1818.36738695 2543.73575463
 2519.58345517 2531.62240094 3176.39009696 2894.40557541 2459.05555235
 2200.25425212 1860.4033702  2775.41648547 2696.30868289 3042.59190443
 1922.90483677 2749.5551466  3098.91578392 1626.32503523 2375.89435766
 3009.03768871 2474.31196289 1840.15990024 1960.53802689 1819.13101587
 2510.83777734 2784.38894323 2905.11306562 2434.23454344 2140.1417314
 2148.4735234  2738.48791652 1385.33783797 2252.76649901 2032.13272498
 1910.63309926 2982.40045723 1605.17475621 1774.85896216 2485.13296918
 3191.63998525 1949.94020302 2792.46014354 2543.95208858 2047.56579659
 2788.40512792 2644.93447122 2237.32401048 2796.7762563  2605.61494811
 2849.65253267 1839.42880639 2604.79272967 1832.67632287 1831.2891858
 2658.36412393 1715.4193271  1727.63926722 1548.15448101 2667.95147022
 2331.18833009 2932.86060739 2109.38193914 2830.75298157 2335.84527681
 2780.64244676 2173.49634756 2595.61545064 2502.64507633 3368.68645622
 2712.63374831 1307.09093875 2391.95302665 2240.07245225 1815.78631114
 2238.55929475 2387.39582295 1879.1712669  2556.53205734 1877.83248889
 1953.41630455 2074.77594619 2635.84878816 2372.79916949 3064.22864629
 3338.57895434 2062.22847694 2816.89918592 3059.146392   2824.1346487
 2532.89370946 2605.29688096 2495.57973588 2976.69811812 2648.80001096
 2294.5093464  2109.04414235 2135.2190408  1731.24410752 1424.22971311
 2585.93308917 2224.39629493 3290.78285517 2887.47357617 2808.15181259
 2554.64803523 2944.74990867 1710.22752468 2526.50262358 1699.33335856
 1440.08250831 2863.50053823 1962.42293762 1692.68826982 2785.70319985
 1769.63662546 2662.22217693 1420.43568465 2575.67904395 2541.03730248
 1673.58354999 1961.53078453 3053.03520322 2132.80695808 2023.84805129
 2516.71221376 1886.49610758 2244.89934444 2797.69480021 2201.56264249
 2408.3073991  2631.81988866 2072.17659317 2546.87714565 2624.02271056
 1471.92756614 3421.7485278  2106.05428672 2228.60328282 3206.37549609
 2907.5068951  2981.63255265 2467.71098275 1587.43097599 1810.42427334
 3141.50526097 2566.60373821 1910.0356042  1835.02642384 2376.89569245
 1819.61493537 1347.21925912 2231.40279833 3343.38613245 2286.15508798
 2371.91571158 2213.45595017 2098.81265552 2206.98512571 2104.39779134
 2857.12252604 2581.39227673 2775.49102003 1509.51254694 1841.05931818
 1733.33523664 1824.37839878 2914.16047672 2242.04844347 2378.92498612
 1758.50347085 1056.56875571 2491.09265539 3120.13780637 2759.71079066
 1981.92889746 1577.86739025 2995.85018396 1825.85885073 1784.0810097
 2446.74068657 1833.47983146 3126.48727687 1681.74835444 1433.85147174
 3135.05847959 1505.82003136 1649.57067854 2118.16218116 2463.69117765
 2984.19954053 2030.69843604 2586.07033623 2272.0678388  1592.23428701
 2592.92931983 2695.52596082 2088.3195905  1809.49059624 2725.18058199
 2940.24470828 2124.6820442  2244.25723355 2374.82280331 1717.23761299
 1876.40603445 3371.03057318 2814.15376039 2545.8205752  2798.68594945
 2187.49234372 1919.81961042 1334.97674367 1786.1112296  1849.3055795
 2345.34163991 2686.66144421 1875.76362768 2044.09016974 2440.98166689
 2298.73436518 1883.84459597 1974.92666614 2631.19628579 1977.83727078
 2193.2336688  2326.19244776 3362.59979806 1569.09870982 1956.15896714
 1607.64664712 2194.72445727 1502.43543856 2232.41625144 3174.81332351
 2146.99166847 2536.76840221 2542.12869253 2120.46137057 1696.66941044
 2442.63373716 1786.99078584 2021.68860148 2577.97769827 2992.23427298
 1326.33908694 1849.78868577 2079.99394401 2184.31657346 2508.15055074
 1376.65935475 1810.86309459 3080.63462601 2336.9174838  2958.67037104
 2589.83451498 2889.01768752 2986.86176347 1990.29295788 2083.43226482
 1942.77431489 1001.16347227 2635.24093791 2067.93459188 1977.48448552
 1778.58553872 1928.64258558 2865.64012825 2212.57674908 2638.13439484
 2367.28449311 2898.0989997  1858.4389626  2571.67253689 2509.52445315
 2163.67178037 2446.37194349 2364.64413635 2160.84983611 1889.71127393
 2639.4139472  2838.24521493 2691.98046297 2028.19310741 2099.73240373
 1894.4826341  2713.88466277 1600.82590541 1263.97699409 2679.92422616
 2076.74217359 2382.66571856 1254.39168692 3332.5585711  2714.00635577
 1740.48926753 2043.19614641 1843.34429853 2594.55934689 1509.03540149
 2609.62932757 1527.37295645 2597.34388575 2423.28686477 1731.03836768
 2481.34411699 2249.14812079 2884.37412592 2374.36835027 1756.9579099
 2033.2755077  2160.79926114 2690.06290875 2071.4965638  1079.15667215
 2926.2703405  2302.51317513 1600.16813579 2390.49344256 1935.00741034
 1962.74997065 2226.44584092 2020.53826161 2595.93801934 2150.24775974
 1916.58542867 2488.68047597 1681.34322493 1714.67046763 2555.39268562
 1740.33039594 2057.37700801 2638.53203057 2659.17117761 2596.56506251
 1898.8361361  2496.32630848 2768.5606142  1725.69419868 2416.09682713
 2797.5333227  1984.91301951 2633.55699237 2600.60044142 2225.20949188
 2223.3537856  2792.60354984 2045.31285431 1912.42763526 1890.93348982
 1212.08220378 2326.1532654  2102.19401498 2167.4992124  3384.64695552
 2391.3658373  2816.55939676 2438.22327446 2748.99675011 1702.23698845
 2450.61523894 2637.46457967 3472.20834327 2536.78248558 1617.69927536
 1799.99905784 2540.37613058 2053.37820323 2106.82237836 2480.76722785
 1615.26479283 2215.93432749 2727.89449245 2196.79930711 1331.8744076
 2817.63057804 1474.2268364  2288.24409112 1784.66540262 1803.39454668
 2593.86718163 2303.13283242 2368.6859758  2726.76823772 1917.4098417
 1847.99003515 3583.95973657 1696.44271251 1541.28555812 1707.4723025
 1450.88972684 2554.1312828  2733.41786441 1580.97446095 2952.01004021
 2653.90203185 2208.67291519 1568.27333408 2546.87647603 2804.92073891
 2794.65757179 2054.72082669 2186.53467786 2240.95013695 2661.47369921
 2751.97173123 2339.02097363 3111.4227516  2786.89797891 2678.85595287
 2082.52589794 2161.98528458 1203.85752508 1131.5920419  2637.1991351
 1071.33849882 1973.47746255 2133.75938641 1905.05827898 2693.23466435
 2740.78728554 2509.67668061 2262.92203044 2403.47850532 2565.68135679
 2512.17416973 1386.11736995 2364.15664413 1950.07913515 1876.66779902
 2765.52237965 2881.10679549 2685.32325671 1595.67537074 1786.64784627
 1862.53875238 2790.20036394 2314.03274993 2797.56926712 1330.75234945
 2907.74803991 2081.63879414 2041.79141855 1702.27251017 1923.7730386
 2178.33186165 1649.13037318 2445.03656051 2045.28662031 2731.52047594
 2394.69671968 2466.25533331 2118.49084523 2021.03456044 2074.35762165
 2534.84212346 2495.75256219 1613.47113495 3233.94018814 1937.97546776
 2586.23246602 2229.33778259 1617.88619926 2809.57014277 2358.15741972
 2104.63654742 2514.91900431 2341.93888621 3230.67019023 2129.02640863
 1602.81856487 2174.19725536 2572.41820564 2694.34007434 1748.00286524
 2712.56580782 2807.84479855 2638.8535491  1423.48604217 2746.31754115
 2566.41645483 1851.55271122 2499.14501977 1967.15955196 1876.06944726
 3143.89072807 3229.44894583 3375.97586269 1585.49957848 1649.88995708
 3014.40476902 2853.67221598 3132.37019543 2306.56050429 2092.42674798
 2593.21543322 2584.65439601 1787.1790984  1950.98759991 1766.94201965
 2319.41521221 2887.68495335 1950.98616568 3035.0847801  2185.25621631
 2247.79614801 2196.16207834 1961.28455803 2246.78072634 1902.69145283
 1354.29526913 1562.44275385 2122.80045883 2114.18218428 3195.8847995
 1776.26979743 2906.23163863 2147.61923339 2007.26650721 3160.36675346
 2434.69165519 2971.79683397 2218.91621574 2364.86752402 1782.16117315
 1541.97585236 1835.87738    2660.47576157 2237.53324368 1895.8450626
 2278.49116517 2574.66906624 1747.91663157 1424.65361375 2774.0259433
 2737.92842522 2515.86273345 2170.93209932 2096.01998751 2947.05434758
 3035.33476432 2699.46608587 1854.56598397 2682.98890755 2949.30314558
 1721.0202809  2379.88324818 1472.79025987 2240.19408414 1621.54174662
 2524.39358783 2693.55825302 1939.2224233  1984.42655258 1822.52880364
 2107.62609671 2375.41485766 2457.43579045 2053.3137131  2024.47819908
 2481.43756713 2948.20124079 1811.43179321 1808.13966088 2027.76650819
 2589.46530654 2212.91012347 3115.20142014 2046.13295939 2890.58918487
 1537.35024684 1857.74463552 1915.7599998  2686.79057449 2479.31578914
 2018.49807436 2826.39852457 2147.08710478 2041.64262659 2025.20889334
 2051.65786464 2291.59240774 2082.01527661 2298.63578515 1743.59621945
 1974.85215235 1421.03808293 2530.37322478 1464.26139559 1671.93745948
 1852.71210978 3004.98274505 2086.10218006 2451.61267557 2318.81007512
 2525.34737893 2170.77805962 2683.55275377 1928.444988   2500.52057047
 2309.78301768 2629.97967167 3304.41586503 1215.94512011 2984.58249144
 2403.83872999 2059.20142709 2110.27236492 1653.89570617 2488.78549468
 1640.49767759 1741.66092966 2110.48157785 2571.87453341 2228.25446028
 1629.25757237 2338.7494913  1928.64277145 3310.18653215 2874.53897139
 1830.24021923 2667.93421451 1810.53313338 3019.19541946 1944.85053855
 3051.60701464 2214.00793087 1891.83702896 2046.31017666 2708.99773997
 2115.13054133 1770.32313162 2040.58513229 2766.67367754 3546.702049
 1801.18628527 1819.55146628 2716.31666919 1411.24156908 2015.59918268
 2534.01605665 2374.11848106 1914.33403958 2888.52431987 1872.77377823
 2405.41418156 2217.29043299 1875.53207072 2428.82736954 1948.28540551
 2163.8531832  2170.76259787 2056.20253055 1298.60534089 2084.77824132
 1949.17472538 1987.08010105 3170.81127458 2612.89713797 2389.16026035
 2294.7748126  1674.90390521 2674.97802388 2119.56494828 1784.27480961
 2198.5138752  2596.9175775  1995.1344196  2705.24987258 1621.71206414
 2121.9947309  2399.96361459 1580.20414689 2778.09701736 2871.47410686
 2082.78116077 1862.63589051 1492.90894054 2366.08586605 1441.68651762
 2660.98384993 2082.94798694 2312.72158696 2470.13017684 3111.05470802
 1577.40338661 3310.99767246 2943.04966178 2519.01734128 1457.0215014
 1691.28455011 2554.50925584 2355.59276267 1994.38079885 1841.97646524
 2257.41497545 2241.73413859 2116.21039738 2809.27761963 2301.38366006
 1700.54366222 2694.78402734 1848.43104125 2084.09835541 1230.67601563
 1303.21931914 2871.47405806 2971.79358568 2888.94876992 2233.99731176
 2021.12384013 2371.91458368 2472.24213497 2153.62711702 1899.08553451
 2312.60782388 1564.84825294 2136.90248772 2443.68492869 3017.25969591
 2400.36015848 2839.41195703 2261.02458757 1370.53687646 1367.88528962
 1811.74734392 2803.64254099 2022.81331461 1964.41817893 2174.18647103
 2308.52683902 2142.14142853 2443.70145397 1983.34782412 2734.44180731
 3323.77401989 2562.14971306 2282.48008281 2410.12697932 3336.42713124
 2121.87740938 2644.24080982 2914.65210997 2183.6261796  2199.46735259
 3138.20754693 3144.88148142 3107.36554144 2620.12625072 2166.57949359
 3168.36758948 1547.54133613 2239.61808355 1535.98582305 1534.94158734
 1890.71766776 1293.96453714 2198.93225931 2218.49585506 2898.50486689
 2007.28196693 2401.22301566 1619.8847902  2570.72230439 2528.53645589
 1859.14421642 2465.51722451 2558.71884133 1215.19551337 2387.86479973
 1861.62442696 1644.41322903 2857.22796782 1352.28412952 2383.69468002
 1877.09465348 3292.60414295 2995.21545862 2498.41472131 2910.22345067
 2121.63996061 3227.57149702 2185.31822259 2263.39207471 1909.01238928
 2303.96086971 2415.68656522 2287.12283709 1743.31702668 1711.20544225
 2212.1222263  1960.59461454 2009.95769217 2221.64791661 1517.14285611
 2473.19164431 2192.88711258 2064.07124287 3112.59868473 2633.70312123
 2072.81516994 2876.9319248  1820.73856598 2794.38998543 2442.87749241
 1956.69189641 3449.06116283 2464.67506404 2571.29376284 2206.29403828
 2112.10977194 2021.17382915 2428.9798009  2691.50745137 2300.5620131
 2533.11503071 1603.43100095 1601.23289632 3368.44564217 2095.86502626
 2442.39302905 2122.07581848 2247.27444603 1927.70491988 1740.52038234
 2023.08304092 1367.99854914 1949.5206436  1811.78301657 2296.12190034
 1794.45812464 1297.80825478 2279.28895932 2417.75553256 2084.12422701
 1670.0839712  2254.15311281 1785.50927839 2032.77463648 2719.1497215
 2308.19405179 2196.35193786 2439.85750584 1726.12213222 2599.16466923
 1755.02005569 3360.88695199 2687.55459411 2117.05029375 3258.60021133
 1363.61148651 2546.45324447 2733.11373085 2191.65726815 1888.11169272]

In [89]:
r2 = r2_score(test_y, predictions)
mae = mean_absolute_error(test_y, predictions)
mse = mean_squared_error(test_y, predictions)
rmse = np.sqrt(mse)

print(f"R² Score: {r2:.3f}")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

R² Score: 0.971
MAE: 28.46
MSE: 7422.07
RMSE: 86.15

In [90]:
model_acc_rf = r2
print(round(model_acc_rf * 100, 4), "%")

97.1483 %

In [91]:
pickle.dump(model_rf, open('model_rf.pkl', 'wb'))

In [92]:
model_rf = pickle.load(open('model_rf.pkl', 'rb'))